<?php

namespace ContainerQz8XE3S;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3bcQSOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3bc_qSO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3bc_qSO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'paiement' => ['privates', '.errored..service_locator.3bc_qSO.App\\Entity\\Paiement', NULL, 'Cannot autowire service ".service_locator.3bc_qSO": it references class "App\\Entity\\Paiement" but no such service exists.'],
        ], [
            'paiement' => 'App\\Entity\\Paiement',
        ]);
    }
}
