<?php

namespace ContainerBInhxM5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EkOp9OIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ekOp9OI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ekOp9OI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'client' => ['privates', '.errored..service_locator.ekOp9OI.App\\Entity\\Client', NULL, 'Cannot autowire service ".service_locator.ekOp9OI": it references class "App\\Entity\\Client" but no such service exists.'],
            'payment' => ['privates', '.errored..service_locator.ekOp9OI.App\\Entity\\Paiement', NULL, 'Cannot autowire service ".service_locator.ekOp9OI": it references class "App\\Entity\\Paiement" but no such service exists.'],
            'product' => ['privates', '.errored..service_locator.ekOp9OI.App\\Entity\\Product', NULL, 'Cannot autowire service ".service_locator.ekOp9OI": it references class "App\\Entity\\Product" but no such service exists.'],
        ], [
            'client' => 'App\\Entity\\Client',
            'payment' => 'App\\Entity\\Paiement',
            'product' => 'App\\Entity\\Product',
        ]);
    }
}
