<?php

namespace ContainerBInhxM5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GFLNC3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gFLN_c3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gFLN_c3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'paiementRepository' => ['privates', 'App\\Repository\\PaiementRepository', 'getPaiementRepositoryService', true],
        ], [
            'paiementRepository' => 'App\\Repository\\PaiementRepository',
        ]);
    }
}
