<?php

namespace Container6akZPsk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OBg0uQZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oBg0uQZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oBg0uQZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'order' => ['privates', '.errored..service_locator.oBg0uQZ.App\\Entity\\Order', NULL, 'Cannot autowire service ".service_locator.oBg0uQZ": it references class "App\\Entity\\Order" but no such service exists.'],
            'paiementRepository' => ['privates', 'App\\Repository\\PaiementRepository', 'getPaiementRepositoryService', true],
            'productRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
        ], [
            'order' => 'App\\Entity\\Order',
            'paiementRepository' => 'App\\Repository\\PaiementRepository',
            'productRepository' => 'App\\Repository\\ProductRepository',
        ]);
    }
}
