<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBInhxM5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBInhxM5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBInhxM5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBInhxM5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBInhxM5\App_KernelDevDebugContainer([
    'container.build_hash' => 'BInhxM5',
    'container.build_id' => 'fcb368a1',
    'container.build_time' => 1625218819,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBInhxM5');
